// Login

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Onboarding

export const SEND_VERIFICATION_CODE_SUCCESS = 'SEND_VERIFICATION_CODE_SUCCESS';
export const SEND_VERIFICATION_CODE_ERROR = 'SEND_VERIFICATION_CODE_ERROR';

export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_ERROR = 'VERIFY_CODE_ERROR';

export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_NAME = 'SET_NAME';
export const SET_EMAIL_ADDRESS = 'SET_EMAIL_ADDRESS';
export const SET_PHONE_NUMBER_VERIFIED = 'SET_PHONE_NUMBER_VERIFIED';
